### ISSUE TITLE
Disassembler

### ISSUE THREAD

**Issue by zephyyrr** [zephyyrr/soda#12]
Soda should have its very own disassembler to go with cola. How about "rum"?

**Comment by Victorystick** [comment]
I was thinking it should just be a command line option to cola. `objdump` uses `--disassemble` (and `-d`). Perhaps we should do something similar? It'll be fewer separate binaries that way.

Just one, to and from assembly.

**Comment by zephyyrr** [comment]
-d is taken by debug.
So it is either -r for reverse or -disassemble.
We could also technically merge verbose and debug into one flag -v to free it for disassemble

**Comment by zephyyrr** [comment]
I am sorry. I  got it mixed up with svm. -d i free for use by disassemble.
